### ISSUE TITLE
[Resource] es_MX / es_ES translation

### ISSUE THREAD

**Issue by Dorzar** [crazysnailboy/CombinedPotions#4]
//Translate by: Dorzar / VeryHardChamp
//Act.: 30/07/2017
item.combined_potion.name=Posión combinada
item.combined_splash_potion.name=Posión combinada arrojadiza
item.combined_lingering_potion.name=Posión combinada persistente
item.combined_tipped_arrow.name=Flecha encantada combinada

**Comment by crazysnailboy** [comment]
Thank you for the translation :)
